import { test, expect } from '@playwright/test';
import { assertInputResponds, assertMobilePlayable, assertPerformanceTuned } from '../../scripts/playability-harness.js';
test.describe('2026-08-01 Pulse Relay', () => {
  test.beforeEach(async ({ page }) => { await page.goto('/games/2026-08-01/index.html'); await page.waitForLoadState('domcontentloaded'); await page.waitForTimeout(500); });
  test('game loads without page errors', async ({ page }) => { const e=[]; page.on('pageerror',x=>e.push(x)); await page.waitForTimeout(500); expect(e).toHaveLength(0); });
  test('game renders core elements', async ({ page }) => { await expect(page.locator('.pads')).toBeVisible(); await expect(page.locator('[data-testid="start-btn"]')).toBeVisible(); expect(await page.locator('body').textContent()).toContain('PULSE RELAY'); });
  test('controls produce observable game-state change', async ({ page }) => { await page.locator('[data-testid="start-btn"]').click(); await assertInputResponds(page,{controls:'click/tap',target:'[data-testid="pad-0"]'}); });
  test('the relay target changes on its own to create escalating pressure', async ({ page }) => { await page.locator('[data-testid="start-btn"]').click(); const before=await page.locator('.beam').getAttribute('class'); await page.waitForTimeout(2500); await expect(page.locator('.beam')).not.toHaveAttribute('class',before); });
  test('game survives rapid input and stays responsive', async ({ page }) => { await page.locator('[data-testid="start-btn"]').click(); for(let i=0;i<25;i++){const cls=await page.locator('.beam').getAttribute('class');const pad=cls.includes('cyan')?0:cls.includes('pink')?1:cls.includes('lime')?2:3;await page.locator(`[data-testid="pad-${pad}"]`).click();await page.waitForTimeout(20)} await assertInputResponds(page,{controls:'click/tap',target:'[data-testid="pad-0"]'}); });
  test('game is mobile playable at 375px', async ({ browser }) => { const c=await browser.newContext({viewport:{width:375,height:667},hasTouch:true}),p=await c.newPage(); await p.goto('/games/2026-08-01/index.html'); await p.waitForLoadState('domcontentloaded'); await p.locator('[data-testid="start-btn"]').tap(); await assertMobilePlayable(p,{controls:'tap',buttonSelector:'.pad'}); await c.close(); });
  test('game writes score/high-score key to localStorage', async ({ page }) => { expect(await page.evaluate(()=>localStorage.getItem('pulseRelayHighScore'))).not.toBeNull(); });
  test('game is performance tuned during play', async ({ page }) => { await page.locator('[data-testid="start-btn"]').click(); await assertPerformanceTuned(page,{minFps:30}); });
});
