import { test, expect } from '@playwright/test';
import { assertInputResponds, assertMobilePlayable, assertPerformanceTuned } from '../../scripts/playability-harness.js';
test.describe('2026-07-19 Gridlock Glow', () => {
  test.beforeEach(async ({ page }) => { await page.goto('/games/2026-07-19/index.html'); await page.waitForLoadState('domcontentloaded'); await page.waitForTimeout(500); });
  test('game loads without page errors', async ({ page }) => { const e=[]; page.on('pageerror',x=>e.push(x)); await page.waitForTimeout(500); expect(e).toHaveLength(0); });
  test('game renders core elements', async ({ page }) => { await expect(page.locator('.grid')).toBeVisible(); await expect(page.locator('[data-testid="start-btn"]')).toBeVisible(); expect(await page.locator('body').textContent()).toContain('GRIDLOCK GLOW'); });
  test('controls produce observable game-state change', async ({ page }) => { await page.locator('[data-testid="start-btn"]').click(); await assertInputResponds(page,{controls:'arrows',target:'.cell.player'}); });
  test('a cell click cannot teleport the courier across the grid', async ({ page }) => { await page.locator('[data-testid="start-btn"]').click(); const before=await page.locator('.cell.player').evaluate(el=>[...el.parentElement.children].indexOf(el)); await page.locator('.cell').nth(0).click(); await expect(page.locator('.cell.player')).toHaveCount(1); const after=await page.locator('.cell.player').evaluate(el=>[...el.parentElement.children].indexOf(el)); expect(after).toBe(before); });
  test('game survives rapid input and stays responsive', async ({ page }) => { await page.locator('[data-testid="start-btn"]').click(); for(let i=0;i<30;i++){await page.keyboard.press(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'][i%4]);await page.waitForTimeout(20)} await assertInputResponds(page,{controls:'arrows',target:'.cell.player'}); });
  test('game is mobile playable at 375px', async ({ browser }) => { const c=await browser.newContext({viewport:{width:375,height:667},hasTouch:true}),p=await c.newPage(); await p.goto('/games/2026-07-19/index.html'); await p.waitForLoadState('domcontentloaded'); await p.locator('[data-testid="start-btn"]').tap(); await assertMobilePlayable(p,{controls:'tap',buttonSelector:'.pad button'}); await c.close(); });
  test('game writes score/high-score key to localStorage', async ({ page }) => { await page.locator('[data-testid="start-btn"]').click(); expect(await page.evaluate(()=>localStorage.getItem('gridlockGlowHighScore'))).not.toBeNull(); });
  test('game is performance tuned during play', async ({ page }) => { await page.locator('[data-testid="start-btn"]').click(); await assertPerformanceTuned(page,{minFps:30}); });
});
